### ISSUE TITLE
Searching for Unique keys only?

### ISSUE THREAD

**Issue by taerilan** [derbec/ternarytreap#5]
Hit there, wanted to ask few questions, is it possible to search ternarytreap database instead by prefixes, rather by whole, unique keys, for example if I search for word car, expected result is car and not cars, card, care etc? And is it then possible to update specific entry, and how can I do that if possible, (all the keys would be unique)

https://github.com/derbec/ternarytreap/blob/master/example/bin/main_map.dart

Asking this, as couldn't implement frequency as you suggested, seems you didn't understand my issue, Im using your database for t9 keyboard, so keys and frequency aren't the same, rather, key just points to the value and frequency, for example, word hello will have key 32445, value hello and frequency 7882, if its possible to search database by whole worlds only, then I could solve my issue, by creating two databases, first would hold key 32445 and value hello, which I would search by prefixes and second database would hold key hello and value 7882, which I would search by unique keys, and then if I could update this second database this would then solve my issue with Chinese characters (more on that in the next paragraph). Anyway, just to give you better picture of my use case, at the moment Im storing T9 number translations as keys and words as values, and then I get frequency of each resulting word from another map, which works fine for English and for now (plan to add longer lists, but seems this won't be problem), but maybe I could do all of this inside your database? If its possible to search database by unique keys and to update values in database based on unique keys, though, seems that's not how database functions?

Chinese words issue, have two separate Chinese words lists in your database, one is around 1000 words long and works seamlessly, (well there is some initial lag of half a seconds in rendering results on the screen, but that's just for the initial search, after that it works great, but, this is flutter issue and not ternarytreap). How ever when I search through 65000 Chinese word list, app starts to stutter and work very slow, freezing for longer periods of time even, though I think this is again probably flutter issue, but wanted to ask if you maybe experienced similar issues? Have also English word list as well around 65000 words long and it works really nice and fast, so it is not about list size, but rather I guess its Chinese characters issue. I think that issue is produced when I'm looking for Chinese words frequency inside a map, so if I could use your database to store frequency, this issue would be solved.

Does it matter order by which I add data in your database, if I order the list alphabetically or by numbers, will it work better, than if I just enter all the data randomly? I mean it is easy for me to sort the data before adding it up, but I have to constantly add new data, and then if order of entries doesn't matter, that's great, I just add new entries as user produces them, but if order of adding entries into database maters, then I have to rebuild whole database and initialize it again, which then creates an issue, as it produces lag up to second long when initializing database.

Thank

**Comment by derbec** [comment]
To get exact matching use [] operator:
Example:
     final map = ternarytreap.TTMultiMapList()
        ..add('cards', 'cards value')
        ..add('cart', 'cart value')
        ..add('car', 'car value')
        ..add('cars', 'cars value')
        ..add('carefully', 'carefully value');

      print(map.valuesByKeyPrefix('car')); // Return all values for keys starting with 'car'
      print(map['car']); // Return only values associated with key 'car'

Result:
(car value, cards value, carefully value, cars value, cart value)
[car value]

Note: If you are only interested in mapping unique words to a value, without the prefix matching, then you should instead use the inbuilt Dart Map type.

**Comment by taerilan** [comment]
Thank you very much, thought using ternary treap could help me solve issue with Chinese characters, but figured out, problem is that they aren't efficient to search through in any database, that's why should translate them to Unicode strings.

So there is no difference in searching efficiency when searching for unique keys in-between dart map and trie database! Thank, since I'm already doing this, and everything is working good, I'll just keep it at that.

Also, you didn't answer and I feel that there's no difference in searching efficiency in ternary treap db, in between populating the database with words sorted in alphabetical order and just populating the database with randomly ordered word lists, because ternary treap database orders it self after being populated? Right?

Really grateful for your timely responses

**Comment by derbec** [comment]
>  Im storing T9 number translations as keys and words as values, and then I get frequency of each resulting word from another map, which works fine for English

You are trying to map T9 number => (word, frequency) and then get or update frequency.

First create a class to associate word and frequency:

class WordFrequency {
  WordFrequency(this.word, this.frequency);

  final String word;
  int frequency;

  @override
  String toString() => 'Word: $word, Frequency: $frequency';
}

      final t9TowordFrequency = ternarytreap.TTMultiMapList<WordFrequency>();

      t9TowordFrequency.add('32445', WordFrequency('Hello', 1));
      t9TowordFrequency.add('12345', WordFrequency('Goodbye', 1));

      // Show stored value
      print(t9TowordFrequency['32445']);

      // Update frequency
      final val = t9TowordFrequency['32445']!.first;
      val.frequency = 2;

      // Check updated value
      print(t9TowordFrequency['32445']);

Result:
[Word: Hello, Frequency: 1]
[Word: Hello, Frequency: 2]

**Comment by derbec** [comment]
Also, it doesn't matter what order you insert keys, this won't affect performance.

As you say the data structure reorders itself to maintain balance.

I have not tried Chinese characters in this data structure so interesting to hear result.
