### ISSUE TITLE
Feature request: shortest prefix api

### ISSUE THREAD

**Issue by jtmcdole** [derbec/ternarytreap#6]
Given a TTSet of ['test', 'testOne', 'testTwo', 'testThree'], add a new API to discover the shortest prefix for a query:

```
final prefix = set.shortestPrefix('t'); // returns 'test' 
```

**Comment by derbec** [comment]
There is a function 'longestCommonKeyPrefixByKeyPrefix' in latest version 2.0.5 that will do this.

**Comment by derbec** [comment]
It finds the longest possible prefix shared by the set of keys returned by a query

**Comment by jtmcdole** [comment]
Thanks!
